# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            concrete(dev)
tagline:          
url:              concreted.github.io
paginate:         1
baseurl:          /
author:
  name:           Aric Huang
  url:            github.com/concreted
  email:          arichuang@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/concreted/concreted.github.io
